const ROLES = {
    ADMIN: "ADMIN",
    PROVIDER: "PROVIDER",
    CUSTOMER: "CUSTOMER",
};

const SLOT_STATUS = {
    AVAILABLE: "AVAILABLE",
    BOOKED: "BOOKED",
};

const BOOKING_STATUS = {
    PENDING_PAYMENT: "PENDING_PAYMENT",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
};

const PAYMENT_STATUS = {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
};

module.exports = {
    ROLES,
    SLOT_STATUS,
    BOOKING_STATUS,
    PAYMENT_STATUS,
};